Update identifiers with missing "No" or "Std"
metanorma/pubid-ieee pull request #79
Opened 2022-08-26 10:22 UTC by mico

related #73

2022-08-28 05:52 UTC, ronaldtse requested changes

2022-08-28 05:52 UTC, ronaldtse commented on update_codes.yaml
> +IEEE 1070-1995: IEEE No 1070-1995
I disagree with this. We should not need to change “IEEE xxx” to “IEEE No xxx”.

2022-08-28 05:52 UTC, ronaldtse commented on update_codes.yaml
> +IEEE 1023-2020 (Revision of IEEE Std 1023-2004): IEEE No 1023-2020 (Revision of IEEE Std 1023-2004)
Also disagree. Thanks.

2022-08-28 05:53 UTC, ronaldtse commented
Can’t this just be done by making “Std” and “No” by optional?

2022-08-31 16:30 UTC, ronaldtse requested changes

2022-08-31 16:30 UTC, ronaldtse commented on spec/pubid_ieee/identifier_spec.rb
> +      let(:pubid) { "IEEE 278-1967" }
Can we also set the generated PubID to be "IEEE Std 278-1967"?

2023-02-22 01:05 UTC, ronaldtse commented
@mico can you help update/rebase this PR and merge it? Thanks!

2023-02-22 12:07 UTC, mico commented
@ronaldtse added "Std" type by default. Could you please confirm if it's what you meant?

2023-02-22 14:23 UTC, ronaldtse requested changes

2023-02-22 14:23 UTC, ronaldtse commented on spec/pubid_ieee/identifier_spec.rb
> +      let(:pubid) { "IEEE Std 29-1941 (ASA Std C77.1-1943) (Reaffirmed 1971)" }
For "ASA C77.1-1943" we don't want the "Std".

2023-02-22 14:23 UTC, ronaldtse commented on spec/pubid_ieee/identifier_spec.rb
> +      let(:pubid) { "ANSI Std C50.32-1976 (IEEE Std 117-1974) (Reaffirmed 1984) (Revision of IEEE Std 117-1956)" }
For "ANSI C50.32-1976" we don't want the "Std" added.

2023-02-22 14:23 UTC, ronaldtse commented on spec/pubid_ieee/identifier_spec.rb
> +      let(:pubid) { "ASA Std C37.1-1937 (Reaffirmed 1945)" }
No "Std" here please. Only for "IEEE" prefix.

2023-02-22 14:23 UTC, ronaldtse commented on spec/pubid_ieee/identifier_spec.rb
> +      let(:pubid) { "IEEE Std P802.11aj/D8.0, August 2017" }
The "Pxxxx" ones are not published standards -- they are preliminary projects, so they should not have "Std".

2023-02-22 14:23 UTC, ronaldtse commented on spec/pubid_ieee/identifier_spec.rb
> +      let(:pubid) { "IEEE Std 142-1956" }
This is correct.

2023-02-22 14:23 UTC, ronaldtse commented on spec/pubid_ieee/identifier_spec.rb
> +      let(:pubid) { "ANSI Std C37.0781-1972" }
For ANSI we don't add Std.

2023-02-22 14:23 UTC, ronaldtse commented on spec/pubid_ieee/identifier_spec.rb
> +      let(:pubid) { "ASA Std C37.1-1950" }
For ASA we don't add "Std".

2023-02-22 14:23 UTC, ronaldtse commented on spec/pubid_ieee/identifier_spec.rb
> +      let(:pubid) { "AIEE Std 91-1962 (ASA Std Y32.14-1962)" }
AIEE Standards are old, and we should not add "Std".

2023-02-22 14:23 UTC, ronaldtse commented on spec/pubid_ieee/identifier_spec.rb
> +      let(:pubid) { "IEEE Std 623-1976 (ANSI Std Y32.21-1976, NCTA Std 006.0975)" }
For ANSI and NCTA we don't add Std.

2023-02-22 14:23 UTC, ronaldtse commented on spec/pubid_ieee/identifier_spec.rb
> +      let(:pubid) { "IEEE Std 1076.1 (IEC Std 61691-6 Edition 1.0 2009-12)" }
IEC should not have Std.

2023-02-22 14:23 UTC, ronaldtse commented on spec/pubid_ieee/identifier_spec.rb
> +      let(:pubid) { "IEEE Std P62.44/D15.3" }
"Pxxx" do not add Std because they are not yet published.

2023-02-22 14:24 UTC, ronaldtse commented
> @ronaldtse added "Std" type by default. Could you please confirm if it's what you meant?

Yes that's correct, but only for "IEEE" published documents:
* For other prefixes, ASA, AIEE, ANSI do not add "Std"
* For "IEEE Pxxx" documents they are preliminary projects -- not yet published -- hence not "Standards" and should not have "Std".

2023-03-02 13:53 UTC, ronaldtse approved these changes
Very nice. Thank you @mico !

2023-03-02 13:53 UTC, ronaldtse commented
Very nicely done. Thank you @mico !

2023-03-02 13:54 UTC, merged